In [6]:
import numpy as np
import pandas as pd

In [2]:
def data_summary(num_attributes):
    # Central tendency - mean, median
    tc1 = pd.DataFrame(num_attributes.apply(np.mean)).T
    tc2 = pd.DataFrame(num_attributes.apply(np.median)).T
    
    # Variability - std, min, max, range, skew, kurtosis
    d1 = pd.DataFrame(num_attributes.apply(min)).T
    d2 = pd.DataFrame(num_attributes.apply(max)).T
    d3 = pd.DataFrame(num_attributes.apply(lambda x: x.max()-x.min())).T
    d4 = pd.DataFrame(num_attributes.apply(np.std)).T
    d5 = pd.DataFrame(num_attributes.apply(lambda x: x.skew())).T
    d6 = pd.DataFrame(num_attributes.apply(lambda x: x.kurtosis())).T
    
    # Concatenate
    s = pd.concat([d1, d2, d3, tc1, tc2, d4, d5, d6]).T.reset_index()
    s.columns = ['columns', 'min', 'max', 'range', 'mean', 'median', 'std', 'skew', 'kurtosis']

    return s

In [4]:
df = pd.read_csv('../data/raw/ab_testing.csv')
df.head()

        uid country gender  spent  purchases        date  group device
0  11115722     MEX      F   1595          5  2016-03-08  GRP B      I
1  11122053     USA      M    498          2  2017-07-14  GRP B      I
2  11128688     USA      F   2394          6  2017-09-17  GRP A      I
3  11130578     USA      F   1197          3  2017-11-30  GRP A      I
4  11130759     ESP      M   1297          3  2018-01-10  GRP B      A

In [7]:
data_summary(df[['spent', 'purchases']])

,columns,min,max,range,mean,median,std,skew,kurtosis
0,spent,99.0,12170.0,12071.0,1883.453349,1596.0,1363.906683,1.365817,2.627362
1,purchases,1.0,30.0,29.0,4.544385,4.0,3.102420,1.348301,2.562334